name: Fazer build, teste, e deploy da documentação no GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/sky-sistemas'
  ARTIFACT: 'webDocumentaçãoSKYINFO2-all.zip'
  DOCKER_VERSION: '242.21870'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fazer build da documentação utilizando o build do Writerside
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Salvar os artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
          retention-days: 7
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Baixar os artefatos
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Testar a documentação
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Baixar os artefatos
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Descompactar os artefatos
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir

      - name: Configurar o ambiente do GitHub Pages
        uses: actions/configure-pages@v4

      - name: Empacotar e enviar os artefatos para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Faça o deploy da documentação no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4